#!/usr/bin/env python3
"""AWS Lambda entry point for the hosted AI brief feed.

Why this exists rather than the GitHub Action alone: GitHub's shared scheduler gives this repo
about two scheduled dispatches a day, clustered, with 15-18 hour overnight gaps — measured over
2026-09-17..24, during which a newly added hourly workflow received zero. An hourly brief is not
something that scheduler will deliver. EventBridge fires on time, so the schedule moved here and
the workflow stayed behind as a manual escape hatch.

It runs the same generator the workflow runs (.github/brief-feed/build_brief.py, packaged
alongside) and publishes the same single-orphan-commit shape to the same branch, so either side
can take over from the other and the app cannot tell which one wrote a given brief.

Environment:
  GEMINI_API_KEY   required — the maintainer's Gemini key
  GITHUB_TOKEN     required — fine-grained PAT, Contents: read and write, this repo only
  GITHUB_REPO      default bull88protocol/aurum
  BRIEF_BRANCH     default brief-data
  FORCE            "1" ignores the freshness guard (for a manual test invoke)

Returns a dict; raises on failure so the invocation is recorded as an error and an alarm can see
it. A failure publishes nothing, and the last good brief stays up until the app ages it out.
"""
import datetime as dt
import json
import os

import build_brief
import github_publish

FEED_PATH = "brief_daily.json"

README = """# brief-data

Generated by the `aurum-brief-feed` AWS Lambda (source in `aws/brief-feed/` on `master`), or by
`.github/workflows/brief-feed.yml` when run by hand. Do not edit or merge.
The branch holds a single commit that each run replaces.

The brief is written by Google's Gemini model, grounded with Google Search. It is market
commentary, not investment advice, and it can be wrong.
"""


def _published_age_minutes(text, now_utc):
    """Minutes since the currently published brief was generated, or None if unreadable."""
    if not text:
        return None
    try:
        stamp = json.loads(text)["generated_utc"]
        generated = dt.datetime.fromisoformat(stamp.replace("Z", "+00:00"))
    except (ValueError, KeyError, TypeError):
        return None
    return (now_utc - generated).total_seconds() / 60.0


def handler(event, context):
    gemini_key = os.environ.get("GEMINI_API_KEY", "").strip()
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    repo = os.environ.get("GITHUB_REPO", "bull88protocol/aurum").strip()
    branch = os.environ.get("BRIEF_BRANCH", "brief-data").strip()
    if not gemini_key:
        raise RuntimeError("GEMINI_API_KEY is not set on the function")
    if not token:
        raise RuntimeError("GITHUB_TOKEN is not set on the function")

    force = os.environ.get("FORCE") == "1" or (isinstance(event, dict) and event.get("force"))
    now_utc = dt.datetime.now(dt.timezone.utc)

    published = github_publish.read_published(repo, branch, FEED_PATH, token)
    age = _published_age_minutes(published, now_utc)
    if age is not None and age < build_brief.MIN_AGE_MINUTES and not force:
        # EventBridge is punctual, so this should rarely fire — it is here because a retry, a
        # manual invoke or an overlapping schedule must not spend a second grounded call.
        msg = f"published brief is {age:.0f} min old (< {build_brief.MIN_AGE_MINUTES}) — nothing to do"
        print(msg)
        return {"published": False, "reason": msg}

    feed = build_brief.build_feed(gemini_key, now_utc)      # raises BriefError; nothing published
    body = json.dumps(feed, separators=(",", ":"), ensure_ascii=False)
    commit = github_publish.publish(
        repo, branch,
        {FEED_PATH: body, "README.md": README},
        f"AI brief generated {feed['generated_utc']}",
        token,
    )
    print(f"published {feed['generated_utc']} as {commit[:10]}")
    return {
        "published": True,
        "generated_utc": feed["generated_utc"],
        "commit": commit,
        "signal": feed["brief"]["sig"],
        "score": feed["brief"]["score"],
        "news_items": len(feed["brief"]["news"]),
    }
