#!/usr/bin/env python3
"""AWS Lambda entry point for the hosted FRED feed.

Why this exists rather than the GitHub Action alone: GitHub's scheduler does not deliver. Measured
on this repo across two cron layouts — bunched every 20 minutes, then spread hourly — it fires
roughly two of the day's slots, hours late, and on 2026-09-28 it ran once at 19:44 UTC and missed
20:15, 21:15 and 22:15 entirely. The consequence is not cosmetic: that day the published feed was
two business days behind Treasury's own numbers, so every install's Gold Index was scoring stale
yields. EventBridge fires on time.

It runs the same builder the workflow runs (.github/fred-feed/build_feed.py, packaged alongside)
and publishes the same single-orphan-commit shape to the same branch, so either side can take over
from the other and the app cannot tell which one wrote a given feed.

Unlike the brief, this is safe to run often: FRED's series are daily, a run that finds nothing new
publishes nothing, and the maintainer's key makes three requests per invocation against a limit of
about 120 a minute.

Environment:
  FRED_API_KEY   required — the maintainer's FRED key
  GITHUB_TOKEN   required — fine-grained PAT, Contents: read and write, this repo only
  GITHUB_REPO    default bull88protocol/aurum
  FRED_BRANCH    default fred-data

Returns a dict; raises on failure so the invocation is recorded as an error. A failure publishes
nothing and the last good feed stays up until the app ages it out (FredFeedClient.MAX_STALE_DAYS).
"""
import json
import os

import build_feed
import github_publish

FEED_PATH = "fred_daily.json"

README = """# fred-data

Generated by the `aurum-fred-feed` AWS Lambda (source in `aws/fred-feed/` on `master`), or by
`.github/workflows/fred-feed.yml` when run by hand. Do not edit or merge.
The branch holds a single commit that each run replaces.

This product uses the FRED® API but is not endorsed or certified by the Federal Reserve Bank of
St. Louis. https://fred.stlouisfed.org/docs/api/terms_of_use.html
"""


def handler(event, context):
    fred_key = os.environ.get("FRED_API_KEY", "").strip()
    token = os.environ.get("GITHUB_TOKEN", "").strip()
    repo = os.environ.get("GITHUB_REPO", "bull88protocol/aurum").strip()
    branch = os.environ.get("FRED_BRANCH", "fred-data").strip()
    if not fred_key:
        raise RuntimeError("FRED_API_KEY is not set on the function")
    if not token:
        raise RuntimeError("GITHUB_TOKEN is not set on the function")

    feed = build_feed.build_payload(fred_key)        # raises FeedError; nothing published
    series = feed["series"]

    # Publish only on a change. FRED's series are daily, so most invocations are no-ops — and a
    # no-op that still force-pushed would rewrite the branch several times a day for nothing.
    published = github_publish.read_published(repo, branch, FEED_PATH, token)
    previous = None
    if published:
        try:
            previous = json.loads(published).get("series")
        except ValueError:
            previous = None
    if series == previous:
        last = max(s["dates"][-1] for s in series.values())
        print(f"unchanged through {last} — nothing to do")
        return {"published": False, "last_date": last}

    last_date = max(s["dates"][-1] for s in series.values())
    commit = github_publish.publish(
        repo, branch,
        {FEED_PATH: json.dumps(feed, separators=(",", ":"), ensure_ascii=False),
         "README.md": README},
        f"FRED feed through {last_date}",
        token,
    )
    print(f"published through {last_date} as {commit[:10]}")
    return {
        "published": True,
        "last_date": last_date,
        "commit": commit,
        "series": {k: v["dates"][-1] for k, v in series.items()},
    }
